build:
  version: "2.0"

accounts:
  message: "Welcome to accounts related QA APIs"
  contactDetails:
    name: "Harun Kaya"
    email: "harun.kaya@gmail.com"
  onCallSupport:
    - (544) 234-4907
    - (589) 123-9099