spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related prod APIs"
  contactDetails:
    name: "Sevda Yilmaz"
    email: "sevda.yilmaz@gmail.com"
  onCallSupport:
    - (777) 956-4564
    - (888) 345-0982